version: '3.9'

services:
  pg_grupoa:
    container_name: pg_grupoa
    image: postgres:14.2-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    tty: true
    networks:
      - network
    healthcheck:
      test: [
        "CMD",
        "pg_isready",
        "-U",
        "${DB_USER}",
      ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  pg_grupoa_test:
    container_name: pg_grupoa_test
    image: postgres:14.2-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    ports:
      - ${DB_PORT_TEST}:5432
    tty: true
    networks:
      - network
    healthcheck:
      test: [
        "CMD",
        "pg_isready",
        "-U",
        "${DB_USER}",
      ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

networks:
  network:
    driver: bridge